Web/src/Entity/Abonnement.php
<?php

namespace App\Entity;

use App\Repository\AbonnementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AbonnementRepository::class)
 */
class Abonnement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_fin;

    /**
     * @ORM\OneToOne(targetEntity=User::class, cascade={"persist", "remove"})
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

Web/src/Controller/AbonnementController.php
<?php

namespace App\Controller;

use App\Repository\AbonnementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AbonnementController extends AbstractController
{
    /**
     * @Route("/abonnements", name="abonnements")
     */
    public function index(AbonnementRepository $abonnementRepository): Response
    {
        return $this->render('abonnement/index.html.twig', [
            'sub'=>$abonnementRepository->findOneBy(['user'=>$this->getUser()]),
        ]);
    }

    /**
     * @Route("/myabonnement", name="myabonnement")
     * @param AbonnementRepository $abonnementRepository
     * @return Response
     */
    public function listAbonnements(AbonnementRepository $abonnementRepository): Response
    {
        return $this->render('abonnement/mySubscription.html.twig', [
            'sub'=>$abonnementRepository->findOneBy(['user'=>$this->getUser()])
        ]);
    }
}

Web/templates/abonnement/ab1.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <!-- Start All Pages -->
    <div class="all-page-title page-breadcrumb">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Card Info</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Pages -->

    <!-- Start blog details -->
    <div class="blog-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-title text-center">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-8 col-lg-8 col-12">
                    <div class="blog-inner-details-page">
                        <div class="blog-inner-box">

                            <div class="inner-blog-detail details-page">
                                <form action="{{ path('confirmpayment1') }}" id="payment-form">

                                    <label for="card-element">
                                        Credit or debit card
                                    </label>
                                    <div id="card-element">
                                        <!-- A Stripe Element will be inserted here. -->
                                    </div>


                                    <!-- Used to display Element errors. -->
                                    <div id="card-errors" role="alert"></div>

                                    <center><button style="margin-top: 2em;
                        background-color: #E7AB3C;
                        border: none;
                        padding: 0.5em;
                        width: 150px;
                        border-radius: 5px;
                        font-family: Quicksand,sans-serif;
                        font-weight: bold;
                        color: #ffffff">Confirm</button></center>
                                </form>




                            </div>
                        </div>


                    </div>
                </div>

                {# Right #}



            </div>
        </div>
    </div>

    <!-- End details -->
{% endblock %}

Web/templates/abonnement/ab2.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <!-- Start All Pages -->
    <div class="all-page-title page-breadcrumb">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Card Info</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Pages -->

    <!-- Start blog details -->
    <div class="blog-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-title text-center">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-8 col-lg-8 col-12">
                    <div class="blog-inner-details-page">
                        <div class="blog-inner-box">

                            <div class="inner-blog-detail details-page">
                                <form action="{{ path('confirmpayment2') }}" id="payment-form">

                                    <label for="card-element">
                                        Credit or debit card
                                    </label>
                                    <div id="card-element">
                                        <!-- A Stripe Element will be inserted here. -->
                                    </div>


                                    <!-- Used to display Element errors. -->
                                    <div id="card-errors" role="alert"></div>

                                    <center><button style="margin-top: 2em;
                        background-color: #E7AB3C;
                        border: none;
                        padding: 0.5em;
                        width: 150px;
                        border-radius: 5px;
                        font-family: Quicksand,sans-serif;
                        font-weight: bold;
                        color: #ffffff">Confirm</button></center>
                                </form>




                            </div>
                        </div>


                    </div>
                </div>

                {# Right #}



            </div>
        </div>
    </div>

    <!-- End details -->
{% endblock %}

Web/templates/abonnement/ab3.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <!-- Start All Pages -->
    <div class="all-page-title page-breadcrumb">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Card Info</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Pages -->

    <!-- Start blog details -->
    <div class="blog-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-title text-center">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-8 col-lg-8 col-12">
                    <div class="blog-inner-details-page">
                        <div class="blog-inner-box">

                            <div class="inner-blog-detail details-page">
                                <form action="{{ path('confirmpayment3') }}" id="payment-form">

                                    <label for="card-element">
                                        Credit or debit card
                                    </label>
                                    <div id="card-element">
                                        <!-- A Stripe Element will be inserted here. -->
                                    </div>


                                    <!-- Used to display Element errors. -->
                                    <div id="card-errors" role="alert"></div>

                                    <center><button style="margin-top: 2em;
                        background-color: #E7AB3C;
                        border: none;
                        padding: 0.5em;
                        width: 150px;
                        border-radius: 5px;
                        font-family: Quicksand,sans-serif;
                        font-weight: bold;
                        color: #ffffff">Confirm</button></center>
                                </form>




                            </div>
                        </div>


                    </div>
                </div>

                {# Right #}



            </div>
        </div>
    </div>

    <!-- End details -->
{% endblock %}

Web/templates/abonnement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}<title>Browse Subscriptions</title>{% endblock %}

{% block body %}

    <div class="all-page-title page-breadcrumb">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Subscriptions</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Pages -->

    <!-- Start Menu -->
    <div class="menu-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="special-menu text-center">
                        <div class="button-group filter-button-group">
                            <button class="active" data-filter="*">Subscriptions</button>

                        </div>
                    </div>
                </div>
            </div>
            <div class="row special-list">
                {% if sub is not null %}
                    <blockquote>
                        <div class="col-lg-4 col-md-6 special-grid">
                        <h1> You are Allready subscribed</h1>
                        </div>
                    </blockquote>
                {% else %}
                <div class="col-lg-4 col-md-6 special-grid">
                    <a href="#" class="list-group-item list-group-item-action">
                        <p>1 Month Subscription</p>
                        <p>Description :</p>
                        <p>Get up to 3 Free Tutorials and Courses</p>
                        <p><h3>Price : 100 DT </h3></p>
                        <a href="{{ path('showCard1') }}" style="width: 300px" class="btn btn-primary ">Get</a>
                    </a>

                </div>

                <div class="col-lg-4 col-md-6 special-grid">
                    <a href="#" class="list-group-item list-group-item-action">
                        <p>3 Months Subscription</p>
                        <p>Description :</p>
                        <p>Get up to 5 Free Tutorials and Courses</p>
                        <p><h3>Price : 250 DT </h3></p>
                        <a href="{{ path('showCard2') }}" style="width: 300px" class="btn btn-primary ">Get</a>
                    </a>

                </div>

                <div class="col-lg-4 col-md-6 special-grid">
                    <a href="#" class="list-group-item list-group-item-action">
                        <p>12 Months Subscription</p>
                        <p>Description :</p>
                        <p>Get Unlimited Access to Tutorials and Courses</p>
                        <p><h3>Price : 950 DT </h3></p>
                        <a href="{{ path('showCard3') }}" style="width: 300px" class="btn btn-primary ">Get</a>
                    </a>

                </div>

                {% endif %}


            </div>
        </div>
    </div>
{% endblock %}

Web/templates/abonnement/mySubscription.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <!-- Start All Pages -->
    <div class="all-page-title page-breadcrumb">
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-12">
                    <h1>My Subscription</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Pages -->

    <!-- Start blog details -->
    <div class="blog-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-title text-center">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-8 col-lg-8 col-12">
                    <div class="blog-inner-details-page">
                        <div class="blog-inner-box">

                            <div class="inner-blog-detail details-page">
                                <blockquote>
                                    <h3>Price :</h3> <h3>{{ sub.prix }} DT</h3><br>
                                    <h3>Start Date :</h3> <h3>{{ sub.dateDebut|date('Y m d') }} </h3><br>
                                    <h3>End Date  :</h3> <h3>{{ sub.dateFin|date('Y m d') }} </h3><br>
                                </blockquote>

                            </div>
                        </div>


                    </div>
                </div>

                {# Right #}



            </div>
        </div>
    </div>

    <!-- End details -->
{% endblock %}